tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ff9d70",
        "primary-fixed-dim": "#a3c4ff",
        "inverse-surface": "#2a2c34",
        "primary-container": "#0052ff",
        background: "#f0f4ff",
        surface: "#f8faff",
        "surface-container-highest": "#d6e0ff",
        "on-primary-container": "#ffffff",
        secondary: "#00c950",
        "on-error": "#ffffff",
        "surface-dim": "#e6eeff",
        "on-error-container": "#3d0000",
        "on-tertiary": "#ffffff",
        "on-background": "#0a0c1e",
        "outline-variant": "#b8c2ff",
        "secondary-fixed-dim": "#50ff8c",
        "on-surface-variant": "#334466",
        "tertiary-fixed": "#ffd2b5",
        "primary-fixed": "#e6f0ff",
        "on-tertiary-container": "#fff0e6",
        "surface-tint": "#004ced",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#ff6b35",
        "surface-bright": "#ffffff",
        tertiary: "#ff6b35",
        "on-secondary": "#001405",
        "surface-container-low": "#e8f0ff",
        "inverse-on-surface": "#f0f4ff",
        "secondary-fixed": "#7aff9d",
        outline: "#6677aa",
        error: "#ff4444",
        "on-secondary-container": "#006e2a",
        primary: "#0044ff",
        "secondary-container": "#8fff80",
        "on-tertiary-fixed": "#2a1000",
        "on-primary-fixed-variant": "#0038b6",
        "surface-variant": "#e0e8ff",
        "surface-container-high": "#1a66ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002108",
        "on-primary-fixed": "#001452",
        "inverse-primary": "#a3c4ff",
        "tertiary-container": "#ff8c52",
        "surface-container": "#d4e2ff",
        "on-secondary-fixed-variant": "#00531e",
        "error-container": "#ffdddd",
        "on-surface": "#0a142e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "max-width-desktop": "1200px",
        "margin-desktop": "auto",
        "gutter-mobile": "16px",
        "gutter-desktop": "24px",
        base: "8px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
};
