/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./home.html",
    "./Browse.html",
    "./productlisting.html",
    "./cart.html",
    "./payment.html",
    "./orderTracking.html",
    "./vendor.html",
    "./test-firebase.html",
    "./src/**/*.{js,html}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb692",
        "primary-fixed-dim": "#b7c4ff",
        "inverse-surface": "#2f3133",
        "primary-container": "#0052ff",
        background: "#f9f9fc",
        surface: "#f9f9fc",
        "surface-container-highest": "#e2e2e5",
        "on-primary-container": "#dfe3ff",
        secondary: "#006e2a",
        "on-error": "#ffffff",
        "surface-dim": "#dadadc",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1c1e",
        "outline-variant": "#c3c5d9",
        "secondary-fixed-dim": "#3ce36a",
        "on-surface-variant": "#434656",
        "tertiary-fixed": "#ffdbcb",
        "primary-fixed": "#dde1ff",
        "on-tertiary-container": "#ffded0",
        "surface-tint": "#004ced",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#7a3000",
        "surface-bright": "#f9f9fc",
        tertiary: "#853600",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f6",
        "inverse-on-surface": "#f0f0f3",
        "secondary-fixed": "#69ff87",
        outline: "#737688",
        error: "#ba1a1a",
        "on-secondary-container": "#00732c",
        primary: "#003ec7",
        "secondary-container": "#5cfd80",
        "on-tertiary-fixed": "#341100",
        "on-primary-fixed-variant": "#0038b6",
        "surface-variant": "#e2e2e5",
        "surface-container-high": "#e8e8ea",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002108",
        "on-primary-fixed": "#001452",
        "inverse-primary": "#b7c4ff",
        "tertiary-container": "#ac4700",
        "surface-container": "#eeeef0",
        "on-secondary-fixed-variant": "#00531e",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "max-width-desktop": "1200px",
        "margin-desktop": "auto",
        "gutter-mobile": "16px",
        "gutter-desktop": "24px",
        base: "8px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
