tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#1e40af",
        "primary-container": "#3b82f6",
        "on-primary": "#ffffff",
        "primary-fixed": "#eff6ff",
        "primary-fixed-dim": "#bfdbfe",
        "on-primary-fixed": "#1e3a8a",
        "on-primary-fixed-variant": "#1d4ed8",
        secondary: "#059669",
        "secondary-container": "#d1fae5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#064e3b",
        "secondary-fixed": "#a7f3d0",
        "secondary-fixed-dim": "#6ee7b7",
        "on-secondary-fixed": "#022c22",
        "on-secondary-fixed-variant": "#047857",
        tertiary: "#f59e0b",
        "tertiary-container": "#fef3c7",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#78350f",
        "tertiary-fixed": "#fde68a",
        "tertiary-fixed-dim": "#fcd34d",
        "on-tertiary-fixed": "#78350f",
        "on-tertiary-fixed-variant": "#d97706",
        background: "#fafaf9",
        surface: "#ffffff",
        "surface-container": "#f5f5f4",
        "surface-container-low": "#fafaf9",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e5e4",
        "surface-dim": "#f5f5f4",
        "surface-variant": "#e7e5e4",
        "surface-bright": "#ffffff",
        "on-background": "#1c1917",
        "on-surface": "#1c1917",
        "on-surface-variant": "#57534e",
        outline: "#a8a29e",
        "outline-variant": "#d6d3d1",
        error: "#dc2626",
        "error-container": "#fef2f2",
        "on-error": "#ffffff",
        "on-error-container": "#7f1d1d",
        "inverse-surface": "#292524",
        "inverse-on-surface": "#fafaf9",
        "inverse-primary": "#60a5fa",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "max-width-desktop": "1200px",
        "margin-desktop": "auto",
        "gutter-mobile": "16px",
        "gutter-desktop": "24px",
        base: "8px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
};
